CREATE TABLE bookings (
    booking_id              INTEGER PRIMARY KEY GENERATED ALWAYS AS IDENTITY,
    inmate_id               INTEGER NOT NULL,
    facility_id             INTEGER NOT NULL,
    booking_number          VARCHAR(30) NOT NULL,
    booking_date            DATE NOT NULL,
    booking_time            TIME,
    arresting_agency        VARCHAR(100),
    arresting_officer       VARCHAR(100),
    arresting_officer_rank  VARCHAR(50),
    arrest_location         VARCHAR(150),
    time_of_arrest          TIMESTAMPTZ,
    committing_court_id     INTEGER NOT NULL,
    committ_order_number    VARCHAR(50),
    committment_order_date  DATE,
    offense_commited        VARCHAR(255) NOT NULL,
    offense_category        VARCHAR(50),
    receiving_officer_id    INTEGER NOT NULL,
    status                  VARCHAR(20) NOT NULL DEFAULT 'active',
    created_at              TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    created_by              INTEGER NOT NULL,
    updated_at              TIMESTAMPTZ,
    updated_by              INTEGER,

    CONSTRAINT uq_bookings_booking_number           UNIQUE (booking_number),
    CONSTRAINT fk_bookings_inmate                   FOREIGN KEY (inmate_id)            REFERENCES inmates (inmate_id),
    CONSTRAINT fk_bookings_facility                 FOREIGN KEY (facility_id)          REFERENCES facilities (facility_id),
    CONSTRAINT fk_bookings_committing_court         FOREIGN KEY (committing_court_id)  REFERENCES committing_courts (committing_court_id),
    CONSTRAINT fk_bookings_receiving_officer        FOREIGN KEY (receiving_officer_id) REFERENCES personnel (personnel_id),
    CONSTRAINT fk_bookings_created_by               FOREIGN KEY (created_by)           REFERENCES users (user_id),
    CONSTRAINT fk_bookings_updated_by               FOREIGN KEY (updated_by)           REFERENCES users (user_id)
);
